// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExpressionSerialization
{
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Reflection;
    using System.Linq.Expressions;
    using System.Xml.Linq;
    using ExpressionSerialization;
    using System;
    
    
    #line 1 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class ExpressionSerializerTemplate : ExpressionSerializerTemplateBase
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public virtual string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write(@"using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Xml.Linq;

namespace ExpressionSerialization
{
	//GenerateXmlFromExpressionCore
	public partial class ExpressionSerializer
    {
        
		public XElement GenerateXmlFromExpressionCore(Expression e)
        {
			XElement replace;            
			if (TryCustomSerializers(e, out replace))
				return replace;            			
			");
            
            #line 31 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"

    foreach (Type expressionType in this.GetExpressionTypes())
    {
        string name = expressionType.Name; //expressionType.ToGenericTypeFullNameString();

            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\telse if (e is ");
            
            #line 36 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" )\r\n\t\t\t{\r\n\t\t\t\treturn ");
            
            #line 38 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("ToXElement((");
            
            #line 38 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(")e);\r\n\t\t\t}\r\n");
            
            #line 40 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\t\telse \r\n            return null;            \t\t\t\r\n        }//end GenerateXmlFromE" +
                    "xpressionCore\r\n\r\n\r\n\t\t\t");
            
            #line 48 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"

    foreach (Type expressionType in this.GetExpressionTypes())
    {
        PropertyInfo[] propertyInfos = expressionType.GetProperties();
        
            
            #line default
            #line hidden
            this.Write("\t\tinternal XElement ");
            
            #line 53 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(expressionType.Name));
            
            #line default
            #line hidden
            this.Write("ToXElement(");
            
            #line 53 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(expressionType.Name));
            
            #line default
            #line hidden
            this.Write(" e)\r\n\t\t{\r\n\t\t\tobject value;\r\n\t\t\tstring xName = \"");
            
            #line 56 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(expressionType.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\tobject[] XElementValues = new object[");
            
            #line 57 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyInfos.Length));
            
            #line default
            #line hidden
            this.Write("];\r\n");
            
            #line 58 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"

    for (int i = 0; i < propertyInfos.Length; i++)
    {
        PropertyInfo p = propertyInfos[i];

            
            #line default
            #line hidden
            this.Write("\t\t\tvalue = ((");
            
            #line 63 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(expressionType.Name));
            
            #line default
            #line hidden
            this.Write(")e).");
            
            #line 63 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\tXElementValues[");
            
            #line 64 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("] = GenerateXmlFromProperty(typeof(");
            
            #line 64 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeResolver.ToGenericTypeFullNameString(p.PropertyType)));
            
            #line default
            #line hidden
            this.Write("), \r\n\t\t\t\t\"");
            
            #line 65 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));
            
            #line default
            #line hidden
            this.Write("\", value ?? string.Empty);\r\n");
            
            #line 66 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\t\t\treturn new XElement(xName, XElementValues);\r\n\t\t}//end static method\r\n\t\t");
            
            #line 71 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t}//end ExpressionSerializer class\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 79 "E:\caci\UnitTests\ExSerializSilverlight\T4ExpressionSerializer\ExpressionSerializerTemplate.tt"

	
    Assembly core = typeof(Expression).Assembly;
    
    public IEnumerable<Type> GetExpressionTypes()
    {
        IEnumerable<Type> expressionTypes = from et in core.GetTypes()
                                            where et.IsSubclassOf(typeof(Expression))
                                            && !et.IsGenericTypeDefinition
                                            && et.IsPublic
                                            select et;
        return expressionTypes;
    }
    

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class ExpressionSerializerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
    }
    #endregion
}
